const fs = require('fs');
const dotenv = require('dotenv');
const result = dotenv.config();

if (result.error) throw result.error;
if (!process.env.REACT_APP_SLASH_GRAPHQL_ENDPOINT)
  throw 'REACT_APP_SLASH_GRAPHQL_ENDPOINT not set';
if (!process.env.REACT_APP_SLASH_AUTH_NAMESPACE)
  throw 'REACT_APP_SLASH_AUTH_NAMESPACE not set';
if (!process.env.REACT_APP_AUTH0_CLIENT_ID)
  throw 'REACT_APP_AUTH0_CLIENT_ID not set';

const {
  REACT_APP_SLASH_GRAPHQL_ENDPOINT,
  REACT_APP_SLASH_AUTH_NAMESPACE,
  REACT_APP_AUTH0_CLIENT_ID,
} = process.env;

try {
  let data = fs.readFileSync('deploy/auth0RuleTemplate.js', 'utf8');
  data = data.replace(
    /\$\{REACT_APP_SLASH_GRAPHQL_ENDPOINT\}/g,
    REACT_APP_SLASH_GRAPHQL_ENDPOINT,
  );
  data = data.replace(
    /\$\{REACT_APP_SLASH_AUTH_NAMESPACE\}/g,
    REACT_APP_SLASH_AUTH_NAMESPACE,
  );
  data = data.replace(
    /\$\{REACT_APP_AUTH0_CLIENT_ID\}/g,
    REACT_APP_AUTH0_CLIENT_ID,
  );
  data =
    `// NOTE: Do not edit this file directly. It gets generated from ./auth0RuleTemplate.js\r\n` +
    data;
  try {
    fs.writeFileSync('deploy/auth0Rule.js', data);
  } finally {
    console.log(
      'The auth0Rule.js file was generated. Copy this file to a rule on your auth0 Dashboard',
    );
  }
} catch (err) {
  throw err;
}
